"""Adds category to expense model

Revision ID: 1434b4d5b487
Revises: 447d37d51dcf
Create Date: 2021-04-21 01:31:33.881704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1434b4d5b487'
down_revision = '447d37d51dcf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'expenses', 'categories', ['category_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.add_column('groups', sa.Column('access_code', sa.String(), nullable=False))
    op.add_column('groups', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('groups', sa.Column('name', sa.String(), nullable=False))
    op.create_foreign_key(None, 'groups', 'users', ['created_by'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'groups', type_='foreignkey')
    op.drop_column('groups', 'name')
    op.drop_column('groups', 'created_by')
    op.drop_column('groups', 'access_code')
    op.drop_constraint(None, 'expenses', type_='foreignkey')
    op.drop_column('expenses', 'category_id')
    # ### end Alembic commands ###
