"""Adds categories table / model and relationships.

Revision ID: 3fa55e7a5ae1
Revises: 9611e01ff944
Create Date: 2021-04-19 18:31:31.452089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fa55e7a5ae1'
down_revision = '9611e01ff944'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('journal_group_id_fkey', 'journal', type_='foreignkey')
    op.create_foreign_key(None, 'journal', 'groups', ['group_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'journal', type_='foreignkey')
    op.create_foreign_key('journal_group_id_fkey', 'journal', 'users', ['group_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_table('categories')
    # ### end Alembic commands ###
