"""Adds created_at column to journal

Revision ID: 447d37d51dcf
Revises: 0cfc3162f5b6
Create Date: 2021-04-20 23:32:58.309796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '447d37d51dcf'
down_revision = '0cfc3162f5b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('journal', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('journal', 'created_at')
    # ### end Alembic commands ###
