"""Adds journal entries list to group model.

Revision ID: 9611e01ff944
Revises: f1dbc1fd6e48
Create Date: 2021-04-19 17:19:01.165978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9611e01ff944'
down_revision = 'f1dbc1fd6e48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('journal', sa.Column('group_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'journal', 'users', ['group_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'journal', type_='foreignkey')
    op.drop_column('journal', 'group_id')
    # ### end Alembic commands ###
