"""Fix Journal to transaction relationship.

Revision ID: f1dbc1fd6e48
Revises: e25bd53d1daf
Create Date: 2021-04-19 17:11:26.493448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1dbc1fd6e48'
down_revision = 'e25bd53d1daf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('entry_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'transactions', 'journal', ['entry_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'entry_id')
    # ### end Alembic commands ###
